### ISSUE TITLE
[Feature Request] Personal Dictionary Sync for Premium Accounts

### ISSUE THREAD

**Issue by onnyyonn** [wrenger/obsidian-languagetool#10]
Currently, words added to the personal dictionary are saved locally. For premium accounts, these words can be uploaded to LanguageTool's personal dictionary via the [API](https://languagetool.org/http-api/#!/default/post_words_add). Please consider adding an option to sync between LanguageTool and this plugin's dictionaries.

**Comment by wrenger** [comment]
I've implemented this in version 0.9.0.
