### ISSUE TITLE
Manualy define document lnguage

### ISSUE THREAD

**Issue by gvasco** [wrenger/obsidian-languagetool#4]
I've recently had a situation where the languange of a document wasn't being detected correctly. Tried a few things to see if they worked but the document despite being in english for some reason was being detected as slovak. In any case in the docs I saw there was a way to add a yaml/frontmatter entry to prevent a note from being auto-analysed, and was wondering if a similar thing could be introduced to define document language?

**Comment by wrenger** [comment]
So you want to do something like:

```md
---
author: Panwar, Ashish and Prasad, Aravinda and Gopinath, K
year: 2018
tags: [alloc, mm, os]
lt_language: en-US
---
# Making Huge Pages Actually Useful

Lorem Ipsum...
```

**Comment by gvasco** [comment]
Yes, that looks perfect!

**Comment by wrenger** [comment]
Done in 0a0f3fcfd64080050f6d45f908a93af6200f4872
