### ISSUE TITLE
How do I access the Personal Dictionary?

### ISSUE THREAD

**Issue by XIIMarcel** [wrenger/obsidian-languagetool#5]
I accidentally added a misspelled word to my personal dictionary.
Now I wanted to remove it from there. But how do I access it? They are not listed in the Language Tool applications or on the Internet. I can't find a document under the .obsidian files either (or am I missing this?)
Is it possible that the personal dictionary is not synchronized with the Language Tool account?

In hindsight, I could have posted it under discussion. Sorry.

**Comment by wrenger** [comment]
Good point, this was also a problem of the original plugin. In this new release, I now also use Obsidian's spellcheck dictionary, which can be edited under `Settings / Editor / Spellcheck (cogwheel button)`.

**Comment by XIIMarcel** [comment]
Perfect, thank you!

**Comment by onnyyonn** [comment]
I believe Obsidian's spellcheck dictionary is not used anymore in the latest version of the plugin. Would it be possible to access the new dictionary?

**Comment by wrenger** [comment]
You can now access your dictionary in the LanguageTool settings.
