### ISSUE TITLE
Libreoffice has a offline version extension for Language Tool

### ISSUE THREAD

**Issue by iHarryPotter178** [wrenger/obsidian-languagetool#7]
Is it not possible to integrate the LibreOffice version Language tool to obsidian, as that won't require any docker image or self hosting?
https://extensions.libreoffice.org/en/extensions/show/languagetool

**Comment by wrenger** [comment]
Unfortunately, LanguageTool is Java-based, so it requires a JRE to run. LibreOffice also has some Java components, so it's not that difficult for them to integrate another one.

Obsidian, on the other hand, is based on electron and typescript. So the only option is the web API (public or self-hosted).
Still, the plugin could just download and execute the LanguageTool web server locally. Some VSCode plugins do this. 

However, on mobile platforms, this just does not work as there is usually no JRE available.

**Comment by iHarryPotter178** [comment]
> Unfortunately, LanguageTool is Java-based, so it requires a JRE to run. LibreOffice also has some Java components, so it's not that difficult for them to integrate another one.
> 
> Obsidian, on the other hand, is based on electron and typescript. So the only option is the web API (public or self-hosted). Still, the plugin could just download and execute the LanguageTool web server locally. Some VSCode plugins do this.
> 
> However, on mobile platforms, this just does not work as there is usually no JRE available.

What is the requirement for making web server locally, I never did that, so I don't understand it much..

**Comment by wrenger** [comment]
LanguageTool has a tutorial for that: https://dev.languagetool.org/http-server

It boils down to:
1. Install Java
2. Download the newest version from https://languagetool.org/download/LanguageTool-stable.zip (and extract it)
3. Execute `java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --allow-origin` (in a terminal in the extracted directory)
4. In Obsidian, change the `LanguageTool / Endpoint` settings to `Custom` and `http://localhost:8081`

**Comment by iHarryPotter178** [comment]
Did it, installed it on local machine, now how do I check if it's actually working, in obsidian, I can check on server, but want to check on obsidian…

**Comment by wrenger** [comment]
Well, just open a file and then check the whole document (either by clicking on the bottom right `Aa` or with the command palette `LanguageTool: Check text`). Afterward, you can check for errors in the LanguageTool settings...

**Comment by wrenger** [comment]
> Okay.. Thanks.. It works.. But takes a lot of ram 😢.. I'll use it ocationaly..

Yes, the reason for this is Java, but usually high memory consumption is not really a problem on modern OSs, they just swap and redistribute memory if other applications need more.
