### ISSUE TITLE
Is its use contemplated in the android version?

### ISSUE THREAD

**Issue by Bejab** [wrenger/obsidian-languagetool#8]
Hi, hope you are having a great day! I'm using the android version of obsidian and I wanted to try this plugin however I realize that it doesn't work for me. I click on "check text" but nothing happens even though there are things that are obviously not right in the text, it's like the plugin is not installed. I don't know if there's something I did wrong or it's just not expected to work on Android.

**Comment by wrenger** [comment]
Are there any Errors in LanguageTool settings (`Settings / LanguageTool / Error logs`)?

**Comment by Bejab** [comment]
Hi! No, it doesn't show any errors in the log as far as I can see, I took a video so you can see the problem. It doesn't work while I'm typing either, although as you can see there are grammatical errors in the text.
 https://github.com/user-attachments/assets/a6744b91-abe2-4584-a36e-5b12ecb08280
