### ISSUE TITLE
Premium Connection Not Working

### ISSUE THREAD

**Issue by yewdiva** [wrenger/obsidian-languagetool#9]
Hi!

I'm probably just missing something obvious, but currently when I enter my API info from LanguageTools, nothing seems to happen.

In the web editor Basic LT found 2 errors in my document, Basic LT + Picky Mode found 6 errors, and premium finds 16. Regardless of what I do with the API and link in Obsidian, or what settings I change, it only ever finds 2.

**Comment by wrenger** [comment]
Hi, that is unfortunate. Did you also activate picky mode in Obsidian (Settings / LanguageTool)? 

Also, you probably did change da API endpoint and entered your mail and API token in settings?

**Comment by yewdiva** [comment]
Thanks for the fast reply!

Since posting this I learned this might be an issue on LT's end. Even their own tools (browser extension and MS Word add-in) are doing the same behavior even though they show me as logged in and a premium user. I opened a support ticket with them but don't expect a reply until Tuesday or Wednesday because of the holiday. If they fix whatever broader issue I have but Obsidian is still having issues, I'll open my request again.

As a possibly related note, the endpoint URL that LT displays in my settings is slightly different (https://api.languagetoolplus.com/v2/). I don't know how relevant this is, but figure it's worth mentioning as the /v2/ isn't shown in the Obsidian setting.

**Comment by wrenger** [comment]
> As a possibly related note, the endpoint URL that LT displays in my settings is slightly different (https://api.languagetoolplus.com/v2/). I don't know how relevant this is, but figure it's worth mentioning as the /v2/ isn't shown in the Obsidian setting.

Yes, the v2 is not shown but added automatically by the plugin.
